# Generated by Django 2.0.4 on 2018-04-27 23:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_auto_20180427_1631'),
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='user_add',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_policies', to='vehicle.Profile'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='date_apply',
            field=models.DateField(default=datetime.datetime(2018, 4, 27, 16, 31, 43, 708648)),
        ),
    ]
