# Generated by Django 2.0.4 on 2018-04-27 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_auto_20180427_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='date_apply',
            field=models.DateField(default=datetime.datetime(2018, 4, 27, 16, 39, 31, 447176)),
        ),
    ]
