# Generated by Django 2.0.4 on 2018-04-30 20:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_auto_20180427_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='vehicle.Car', verbose_name='Car Vin number'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='date_apply',
            field=models.DateField(default=datetime.datetime(2018, 4, 30, 13, 21, 59, 141202)),
        ),
    ]
