# Generated by Django 2.0.4 on 2018-04-20 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(choices=[('ho', 'Honda'), ('to', 'Toyota'), ('fo', 'Force'), ('su', 'Suzuki')], default='ho', max_length=20)),
                ('made', models.CharField(choices=[('2018', 2018), ('2017', 2017), ('2016', 2016), ('2015', 2015), ('2014', 2014), ('2013', 2013), ('2012', 2012), ('2011', 2011), ('2010', 2010), ('2009', 2009), ('2008', 2008), ('2007', 2007), ('2006', 2006), ('2005', 2005), ('2004', 2004), ('2003', 2003), ('2002', 2002), ('2001', 2001), ('2000', 2000), ('1999', 1999), ('1998', 1998), ('1997', 1997), ('1996', 1996), ('1995', 1995), ('1994', 1994), ('1993', 1993)], default=2018, max_length=10)),
                ('car_type', models.CharField(blank=True, choices=[('se', 'Sedan'), ('sp', 'Sport'), ('va', 'Van'), ('tr', 'Truck')], default='se', max_length=30)),
                ('date_add', models.DateField(default=datetime.date(2018, 4, 20))),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Full Name')),
                ('dob', models.DateField(blank=True, default=datetime.date(2000, 6, 15), null=True, verbose_name='Date of Birth')),
                ('sex', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=2)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
