# Generated by Django 2.0.4 on 2018-04-23 20:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20180423_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date_add',
            field=models.DateField(default=datetime.datetime(2018, 4, 23, 20, 55, 42, 667513, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_car', to='vehicle.Owner'),
        ),
    ]
