# Generated by Django 2.0.4 on 2018-04-23 21:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_auto_20180423_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date_add',
            field=models.DateField(default=datetime.datetime(2018, 4, 23, 21, 7, 56, 346299, tzinfo=utc)),
        ),
    ]
