# Generated by Django 2.0.4 on 2018-04-24 17:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20180423_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('date_join', models.DateField(default=datetime.datetime(2018, 4, 24, 17, 34, 55, 610592, tzinfo=utc))),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vehicle.Owner')),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='date_add',
            field=models.DateField(default=datetime.datetime(2018, 4, 24, 17, 34, 55, 610592, tzinfo=utc)),
        ),
    ]
