# Generated by Django 2.0.4 on 2018-04-27 23:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_auto_20180427_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='vin_number',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='date_add',
            field=models.DateField(default=datetime.datetime(2018, 4, 27, 23, 31, 43, 705145, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_join',
            field=models.DateField(default=datetime.datetime(2018, 4, 27, 23, 31, 43, 705645, tzinfo=utc)),
        ),
    ]
