# Generated by Django 2.0.4 on 2018-04-27 23:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_auto_20180427_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date_add',
            field=models.DateField(default=datetime.datetime(2018, 4, 27, 23, 39, 31, 445174, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_join',
            field=models.DateField(default=datetime.datetime(2018, 4, 27, 23, 39, 31, 446176, tzinfo=utc)),
        ),
    ]
