# Generated by Django 2.0.4 on 2018-04-30 20:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_auto_20180427_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date_add',
            field=models.DateField(default=datetime.datetime(2018, 4, 30, 20, 21, 59, 134198, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_join',
            field=models.DateField(default=datetime.datetime(2018, 4, 30, 20, 21, 59, 135197, tzinfo=utc)),
        ),
    ]
